### PR TITLE
fix: Ws.waitForVout & clear ping timeout

### PR DESCRIPTION
**Pull request by jojobyte**
Fix browser bug with missing `waitForVout` and `setTimeout` not being cleared.

It happens at this point in my stream https://youtu.be/Hik0sLqudYg?t=3108 for `waitForVout` & https://youtu.be/Hik0sLqudYg?t=3805 for the `setTimeout` issue, after fixing https://github.com/dashhive/dashsight.js/pull/17

### CODE REVIEW

**Review by coolaj86 — APPROVED** [review]
👍

**Comment by riongull** [comment]
Why was this closed with unmerged commits.

Let's make a habit of commenting with the reason(s) in these cases.

**Comment by riongull** [comment]
@jojobyte

**Comment by coolaj86** [comment]
@riongull the commits were included in about her branch.

**Pull request closed without merging**
